### ISSUE TITLE
One-off background tasks

### ISSUE THREAD

**Issue by drairi** [sermoa/hue-dashboard#28]
I want to be able to call a background task to run just once and then automatically delete itself.

Then we can get rid of the POST routes '/light/:lightId/random/:time?' and '/group/:groupId/cycle/:time?'

**Comment by rvedotrc** [comment]
Yeah, I thought that maybe "executionCount" might be nice. (default: infinite)

**Comment by drairi** [comment]
YES!!! I'd be very happy with that!! 😄

**Comment by rvedotrc** [comment]
Fixed by #32
